//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayaInteligenteWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadiaDao
    {
        public int idEstadia { get; set; }
        public System.DateTime entrada { get; set; }
        public Nullable<System.DateTime> salida { get; set; }
        public int codigo { get; set; }
        public string dominio { get; set; }
    }
}
